### ISSUE TITLE
Documentation no longer building successfully with matlabdomain

### ISSUE THREAD

**Issue by kbonney** [sphinx-contrib/matlabdomain#188] opened 2023-05-23 16:46 UTC
Hello matlabdomain devs,
Thank you for your work on this useful extension.

Recently, the documentation for [NuMAD](https://github.com/sandialabs/NuMAD) has been failing to build. On RTD, the build fails due to a timeout error. When I build locally I get the same issue - but I am able to keyboard interrupt (CTRL-C) to get more information. [Here](https://pastebin.com/y1E12B5k) is a pastebin for the full log. 

I checkout out the last [commit that passed the documentation](https://readthedocs.org/projects/numad/builds/16084907/), and attempted to build the documentation - but I encountered the same issue as above. We have pinned the python dependencies used for building the docs, so I am unsure why a previously building commit would no longer build under the same conditions. We have been using an old version of matlabdomain, so I attempted to build the documentation (still on the last working commit) using the latest release (0.19.0) and I get a different error log which can be read [here](https://pastebin.com/tMFX6iAn). Unpinning all requirements and letting pip install the latest compatible versions results in a nearly identical error log.

I am not sure how to interpret these error logs - so any advice on how to proceed would be appreciated.
Please let me know what other information I can provide.
Best,
Kirk

**Comment by joeced** [comment] 2023-05-24 04:31
That looks odd. I'll try to build the docs on my own, to identify the issue. I found a few bugs in version 0.19.0 (among other a possible endless loop), and released 0.19.1 last week.

**Comment by joeced** [comment] 2023-05-26 09:34
Findings:
* I can't reproduce the RTD commit that worked: https://readthedocs.org/projects/numad/builds/16084907/, neither Python 3.8 and 3.11, and by double-checking the "pip freeze".
* There is a bug in `MatClassDocumenter::document_member_section`, filed in #189.

We will try to fix this ASAP.

**Comment by kbonney** [comment] 2023-05-30 16:45
Thanks for the update. Will stand by for the bug-fix.

**Comment by joeced** [comment] 2023-06-07 06:31
Fixed in version 0.20.0rc1.

**Closed by joeced** 2023-06-07 06:31 UTC
