### ISSUE TITLE
NoneType AttributeError in import_object

### ISSUE THREAD

**Issue by dumpadu** [sphinx-contrib/matlabdomain#114] opened 2020-12-03 16:33 UTC
First of all: good work and thanks a lot for the development of this extension.

When I start sphinx with this extension (latest version), the build runs into an exception:

Exception occurred: File "*\python\3.6.5\lib\site-packages\sphinxcontrib\mat_documenters.py", line 917, in import_object if self.object.attrs.get('Static'): AttributeError: 'NoneType' object has no attribute 'attrs'

I added a local security check by extending the condition (if self.object and ...), the build run successfully and the result fits for me.
Is this the right way or is the problem to be found elsewhere?

**Comment by joeced** [comment] 2020-12-03 20:27
Hi. Can you provide a small example that triggers this behavior?

**Comment by Andrey1994** [comment] 2021-01-04 01:50
I see exactly the same, will not provide small example but will send a link to the main project soon

**Comment by Andrey1994** [comment] 2021-01-04 02:37
https://github.com/brainflow-dev/brainflow/pull/202

I've added the same security check, build run with warnings about NoneType obj and seems like some doc string missed

**Comment by joeced** [comment] 2021-01-04 15:06
@Andrey1994 can you point me to the log where I can see the error.

**Comment by Andrey1994** [comment] 2021-01-04 16:24
In requirements replace my fork by upstream version from pypi and you will reproduce it

**Comment by joeced** [comment] 2021-01-04 19:06
When I try to build the docs (on Windows) I run into the following error:
`brainflow\docs>make html
Running Sphinx v3.2.1
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 87 source files that are out of date
updating environment: [new config] 87 added, 0 changed, 0 removed
C:\Users\Jorgen\Documents\github\brainflow\docs\.venv\Lib\site-packages\mne\viz\_brain\tests\test.ipynb:6: WARNING: Each notebook should have at least one section title

Notebook error:
DeadKernelError in .venv\Lib\site-packages\nbclient\tests\files\Autokill.ipynb:
Kernel died
`
Can you please advice?

I see that you set the version of Sphinx to 3.2.1, I tried doing that on the tests, but they all pass.

**Comment by Andrey1994** [comment] 2021-01-04 19:19
I can not reproduce it
```
Notebook error:
DeadKernelError in .venv\Lib\site-packages\nbclient\tests\files\Autokill.ipynb:
```
and in rtd there is no such issue,

Did you use exactly the same versions of all packages from requirements.txt?

**Comment by joeced** [comment] 2021-01-04 20:40
Here's what I did: (Note: I had to remove everything `nbsphinx` related in the `docs/conf.py` file to make it work!)

```
cd brainflow
python -m venv .venv
.venv\Scripts\activate
pip install -r docs\requirements.txt
cd docs
make html
```

Now It will run, but produces warnings.

However, I did try having a Python virtual environment in `docs/.venv/`. This generates the error. It looks like a problem with `autosummary`. There is an old bug (#37) that discusses `autosummary` issues, but I never dived into it.

**Comment by Andrey1994** [comment] 2021-01-04 20:50
Yes, there are warnings about Nonetype object from matlab extension, if you replace matlabdomain package patched by me by upstream package there will be this error instead warnings

**Comment by Andrey1994** [comment] 2021-01-04 20:53
https://github.com/brainflow-dev/brainflow/blob/matlab_docs/docs/requirements.txt#L13

**Comment by Andrey1994** [comment] 2021-01-04 20:54
I dont generate docs in github actions, it uses readthedocs to build it

**Comment by Andrey1994** [comment] 2021-01-04 21:19
You can find deployed docs here https://brainflow.readthedocs.io/en/matlab_docs/UserAPI.html#matlab-api-reference and as you can see there are some doc strings ignored also static methods are not recognized correctly(only the first one recognized as static method). I think its a result of workaround which I applied to original issue mentioned here and real fix needed instead

**Comment by Andrey1994** [comment] 2021-01-04 21:35
I know what was wrong.

I use code style with space before bracket and its 100% valid in matlab, but seems like parser here doesnt expect it and fails

**Comment by joeced** [comment] 2021-01-05 05:31
I'll look at it again tonight. That is why I seek out minimal failing examples - it makes it easier to find the issue :)

**Comment by joeced** [comment] 2021-01-05 19:37
Found the bug - and you were correct. We didn't handle trailing spaces correctly. It is fixed now - and I'll release a new version ASAP. Waiting for travis-ci to build it.

**Closed** 2021-01-05 20:38 UTC
Labels: bug
