### ISSUE TITLE
Class methods with a dot show an underscore instead of dot in the documentation.

### ISSUE THREAD

**Issue by dullin** [sphinx-contrib/matlabdomain#82] opened 2018-11-21 06:02 UTC
I'm using a [Property Get Method](https://www.mathworks.com/help/matlab/matlab_oop/property-get-methods.html) where the method declaration looks like :
`function out = get.PropertyName(obj)`

When rendering the pdf of a method name with a dot, the documentation shows an underscore instead. The previous example would show as get_PropertyName.

**Comment by joeced** [comment] 2018-11-21 07:45
Thanks for the report. Apparently, this is intentional. In https://github.com/sphinx-contrib/matlabdomain/blob/0bda53cd473381e19e7674df101f46fd074dc5a7/sphinxcontrib/mat_types.py#L956 set/get methods get the dot replaced with an underscore. It looks like it has something to do with name lookup. I'll see if I can change the behavior to the the proper dot.,

**Comment by joeced** [comment] 2019-01-10 23:04
@dullin I  have now investigated this, and actually I'm not sure if they should be documented. MATLAB does not show any documentation strings for get/set methods, and according to https://se.mathworks.com/matlabcentral/answers/411344-why-doesn-t-the-methods-command-display-set-property-and-get-property-methods-of-a-class-what, this is expected behavior.

So, the question is, if we should actually document them at all. I could add behavior to actually skip these methods. Do you have an opinion on this.

**Comment by dullin** [comment] 2019-01-11 03:30
I think skipping them is actually the right call in this case. Any documentation that was in the get/set methods would just be relegated to the property description instead. That makes sense since, like it was put forward, the methods themselves aren't callable.

**Comment by joeced** [comment] 2019-02-02 21:18
Fixed in https://github.com/sphinx-contrib/matlabdomain/releases/tag/0.5.0.

**Closed by joeced** 2019-02-02 21:18 UTC
